import { Ad } from './types';

export const MOCK_ADS: Ad[] = [
  {
    id: 'ad-1',
    title: 'Next-Gen Noise Cancelling Headphones',
    company: 'AudioTech',
    description: 'Immerse yourself in pure sound. Our new headphones block out 99% of background noise.',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=1000',
    category: 'Technology',
    type: 'native',
    ctaText: 'Shop Now',
    targetUrl: '#',
  },
  {
    id: 'ad-2',
    title: 'Fresh Organic Produce Delivered',
    company: 'Farm2Door',
    description: 'Get seasonal, locally sourced organic fruits and vegetables delivered straight to your door.',
    imageUrl: 'https://images.unsplash.com/photo-1610348725531-843dff563e2c?auto=format&fit=crop&q=80&w=1000',
    category: 'Food',
    type: 'banner',
    ctaText: 'Get 20% Off',
    targetUrl: '#',
  },
  {
    id: 'ad-3',
    title: 'Minimalist Watches for Everyday',
    company: 'Chrono Designs',
    description: 'Elevate your style with our collection of sleek, minimalist timepieces.',
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=1000',
    category: 'Fashion',
    type: 'native',
    ctaText: 'View Collection',
    targetUrl: '#',
  },
  {
    id: 'ad-4',
    title: 'Master Cloud Architecture',
    company: 'CloudAcademy',
    description: 'Advance your career with hands-on courses in AWS, Azure, and Google Cloud.',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=1000',
    category: 'Education',
    type: 'video',
    ctaText: 'Start Free Trial',
    targetUrl: '#',
  },
  {
    id: 'ad-5',
    title: 'The Ultimate Travel Backpack',
    company: 'Nomad Gear',
    description: 'Weatherproof, expandable, and designed for the modern traveler. Never check a bag again.',
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=1000',
    category: 'Travel',
    type: 'banner',
    ctaText: 'Explore Gear',
    targetUrl: '#',
  },
  {
    id: 'ad-6',
    title: 'Plant-Based Protein Power',
    company: 'GreenGains',
    description: 'Fuel your workouts with clean, delicious plant-based protein powder.',
    imageUrl: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?auto=format&fit=crop&q=80&w=1000',
    category: 'Food',
    type: 'native',
    ctaText: 'Try It Today',
    targetUrl: '#',
  },
  {
    id: 'ad-7',
    title: 'Smart Home Security System',
    company: 'SafeHouse',
    description: 'Keep your family safe with 24/7 monitoring and high-definition smart cameras.',
    imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&q=80&w=1000',
    category: 'Technology',
    type: 'video',
    ctaText: 'Secure Your Home',
    targetUrl: '#',
  },
  {
    id: 'ad-8',
    title: 'Sustainable Summer Collection',
    company: 'EcoWear',
    description: 'Look good and feel good in our new line of clothing made from 100% recycled materials.',
    imageUrl: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&q=80&w=1000',
    category: 'Fashion',
    type: 'banner',
    ctaText: 'Shop Summer',
    targetUrl: '#',
  }
];

export const CATEGORIES = ['All', 'Technology', 'Food', 'Fashion', 'Education', 'Travel'];
